### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (in v3.0.498)

### ISSUE THREAD

**Issue by michaelandlawhall** [mburbea/koar-item-editor#171]
**Describe the bug**
Ps4 bin file does not load to editor and proceeds to list multiple details including not locating equipped items

**To Reproduce**
1. Go to '...' PS4 save file until reaching CUSA17271
2. Click on '....' PS4 save files (*.bin)
3. Click on file within CUSA17271 
4. See error "Loading File"

**System Information**
 - OS: [Windows 11 64 bit]
 - Game version [PS4]
 - Version of the editor: [e.g. 3.0.498] and used latest update previously

**Comment by holytotemic** [comment]
Same is happening for PC save files. 

[Window Title]
KoAR Save Editor

[Main Instruction]
Error Loading File

[Content]
System.IndexOutOfRangeException: Index was outside the bounds of the array.

[^] Hide details  [ ] Open GitHub bug report? (Requires a free account)  [OK]

[Expanded Information]
   at KoAR.Core.GameSave.<.ctor>g__FindEquippedItems|14_7(Int32 playerActor) in D:\a\1\s\KoAR.Core\GameSave.cs:line 166
   at KoAR.Core.GameSave..ctor(String fileName) in D:\a\1\s\KoAR.Core\GameSave.cs:line 146
   at KoAR.SaveEditor.Views.Main.MainWindowViewModel.OpenFile(String fileName) in D:\a\1\s\KoAR.SaveEditor\Views\Main\MainWindowViewModel.cs:line 127
