### ISSUE TITLE
Crash when opening save

### ISSUE THREAD

**Issue by RedKitsune** [mburbea/koar-item-editor#77]
When i try to open my savegame of Re-Reckoning with the v.3.0.251 it automatically crashes the editor and closes it.

What's strange about it is that it affects every one of my saves, except the very first one i made just after speaking to Agarth upon exiting the tower at the start of the game.

At first i thought that it was because of the gamesave compression problem, but apparently it was fixed in the last update, so i'm opening this issue.

Here is the stacktrace that i get in Windows event manager after each crash :

`Application: KoAR.SaveEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument)
   at KoAR.Core.ItemBuffMemory..ctor(KoAR.Core.GameSave, KoAR.Core.Item, Int32, Int32)
   at KoAR.Core.Item..ctor(KoAR.Core.GameSave, Int32, Int32, Int32, Int32, Int32, Int32, Int32)
   at KoAR.Core.GameSave..ctor(System.String)
   at KoAR.SaveEditor.Views.Main.MainWindowViewModel.OpenFile()
   at System.Windows.Input.CommandBinding.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(System.Object, System.Windows.Input.ExecutedRoutedEventArgs, System.Windows.Input.CommandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Windows.Input.CommandBindingCollection, System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(System.Object, System.Windows.IInputElement, Boolean)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at KoAR.SaveEditor.App.Main()`

**Comment by mburbea** [comment]
Could you send a faulting save file?

**Comment by RedKitsune** [comment]
Sure, here is the most recent one that crashes (had to zip it since github doesn't allow the .sav format)
[svd_fmt_5_6.zip](https://github.com/mburbea/koar-item-editor/files/5288229/svd_fmt_5_6.zip)

**Comment by PoroSnax** [comment]
Hello there! I've got quite the same problem. The editor crash when I try to load a save but not the first ones (before 1/2 hour of gameplay).
[save.zip](https://github.com/mburbea/koar-item-editor/files/5288337/save.zip)
(I think I crash after the 5th save)

**Comment by mburbea** [comment]
@RedKitsune I think I see the issue. Your version of the Song is the first item I've ever seen using the inactive buff section of the item buff area. Meaning that the mana stealing it offers is a straight lie. I'll have to add some support for this, older versions of the editor would only read the active buff list, but I recently added support for affix modification which likely is when the crash started happening. 

@PoroSnax , are you using a 3.x release? I'm guessing the issue you're running 2.x release which is erroring as soon as it encounters the stash in the remaster. Also, in the future only include one save file.

**Comment by PoroSnax** [comment]
> @RedKitsune I think I see the issue. Your version of the Song is the first item I've ever seen using the inactive buff section of the item buff area. Meaning that the mana stealing it offers is a straight lie. I'll have to add some support for this, older versions of the editor would only read the active buff list, but I recently added support for affix modification which likely is when the crash started happening.
> 
> @PoroSnax , are you using a 3.x release? I'm guessing the issue you're running 2.x release which is erroring as soon as it encounters the stash in the remaster. Also, in the future only include one save file.

I'm using the latest 3.x release
