### ISSUE TITLE
List of requirements

### ISSUE THREAD

**Issue by txtsd** [mburbea/koar-item-editor#88]
What are the requirements for this to run apart from .NET 4.0?
I'm trying to get this running on Linux via wine, but it's been crashing at launch so far.

Not sure if this error message helps. The rest of it was wine specific.
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'KoAR.SaveEditor.App' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Reflection.CustomAttributeExtensions' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at KoAR.SaveEditor.App..cctor()
   --- End of inner exception stack trace ---
   at KoAR.SaveEditor.App.Main()
```

**Comment by txtsd** [comment]
Here's a trace when trying to run it with .NET 4.8 and Visual C++ Runtime 2019 installed

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.IsDefined(Type attributeType, Boolean inherit)
   at System.Attribute.IsDefined(Assembly element, Type attributeType, Boolean inherit)
   at CModuleInitialize.IsProcessDpiAware(CModuleInitialize* )
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x7914d42b.CreateCModuleInitialize()
   at ?A0x7914d42b.??__E?A0x7914d42b@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
```

**Comment by mburbea** [comment]
I'm not sure, unfortunately this is out of my wheelhouse and not something I've really looked into. The application uses WPF, so there are likely some WPF related dependencies you'll have to look at. Here is a reddit post about it:

https://www.reddit.com/r/linux4noobs/comments/firqs9/getting_windows_wpf_applications_to_run_with_wine/

**Comment by txtsd** [comment]
The instructions in that link don't help. I'll see what else I can find about WPF and wine and report back.

**Comment by txtsd** [comment]
Tried a lot of different things but I couldn't get it to run. Ended up running it in a VM instead.
